export const FIFA_TO_ISO: Record<string, string> = {
  BRA: "br",
  GER: "de",
  USA: "us",
  MEX: "mx",
  JPN: "jp",
  FRA: "fr",
  ENG: "gb",
  ESP: "es",
  ITA: "it",
  POR: "pt",
  NED: "nl",
  BEL: "be",
  ARG: "ar",
  COL: "co",
  URU: "uy",
  CHI: "cl",
  PER: "pe",
  ECU: "ec",
  CAN: "ca",
  AUS: "au",
  KOR: "kr",
  RSA: "za",
  SEN: "sn",
  CMR: "cm",
  NGA: "ng",
  GHA: "gh",
  CIV: "ci",
  MAR: "ma",
  EGY: "eg",
  TUN: "tn",
  ALG: "dz",
  SDN: "sd",
  QAT: "qa",
  UAE: "ae",
  KSA: "sa",
  IRN: "ir",
  IRQ: "iq",
  TUR: "tr",
  AUT: "at",
  SUI: "ch",
  ROU: "ro",
  POL: "pl",
  UKR: "ua",
  RUS: "ru",
  CRO: "hr",
  SRB: "rs",
  DEN: "dk",
  SWE: "se",
  NOR: "no",
  FIN: "fi",
  ISL: "is",
  SCO: "gb-sct",
  WAL: "gb-wls",
  NIR: "gb-nir",
  IRL: "ie",
  CZE: "cz",
  SVK: "sk",
  HUN: "hu",
  GRE: "gr",
  BUL: "bg",
  SVN: "si",
  BIH: "ba",
  MNE: "me",
  ALB: "al",
  GEO: "ge",
  ARM: "am",
  AZE: "az",
  KAZ: "kz",
  UZB: "uz",
  TKM: "tm",
  KGZ: "kg",
  TJ

: "tj",
  NZL: "nz",
  PAN: "pa",
  JAM: "jm",
  HAI: "ht",
  CRC: "cr",
  HON: "hn",
  GUA: "gt",
  PAR: "py",
  BOL: "bo",
  VEN: "ve",
  TRI: "tt",
  BRU: "bn",
  SIN: "sg",
  MAS: "my",
  IDN: "id",
  THA: "th",
  VNM: "vn",
  PHI: "ph",
  IND: "in",
  CHN: "cn",
  HKG: "hk",
  TPE: "tw",
  PRK: "kp",
  CYP: "cy",
  MLT: "mt",
  LUX: "lu",
  AND: "ad",
  MON: "mc",
  SMR: "sm",
  LIE: "li",
  GIB: "gi",
  FRO: "fo",
  CPV: "cv",
  JOR: "jo",
  COD: "cd",
  CGO: "cg",
  CUW: "cw",
};

export const WORLD_CUP_2026_TEAM_ORDER = [
  { fifaCode: "MEX", name: "México" },
  { fifaCode: "KOR", name: "Coreia do Sul" },
  { fifaCode: "RSA", name: "África do Sul" },
  { fifaCode: "CZE", name: "República Tcheca" },
  { fifaCode: "CAN", name: "Canadá" },
  { fifaCode: "SUI", name: "Suíça" },
  { fifaCode: "QAT", name: "Catar" },
  { fifaCode: "BIH", name: "Bósnia e Herzegovina" },
  { fifaCode: "BRA", name: "Brasil" },
  { fifaCode: "MAR", name: "Marrocos" },
  { fifaCode: "SCO", name: "Escócia" },
  { fifaCode: "HAI", name: "Haiti" },
  { fifaCode: "USA", name: "Estados Unidos" },
  { fifaCode: "AUS", name: "Austrália" },
  { fifaCode: "PAR", name: "Paraguai" },
  { fifaCode: "TUR", name: "Turquia" },
  { fifaCode: "GER", name: "Alemanha" },
  { fifaCode: "ECU", name: "Equador" },
  { fifaCode: "CIV", name: "Costa do Marfim" },
  { fifaCode: "CUW", name: "Curaçao" },
  { fifaCode: "NED", name: "Holanda" },
  { fifaCode: "JPN", name: "Japão" },
  { fifaCode: "TUN", name: "Tunísia" },
  { fifaCode: "SWE", name: "Suécia" },
  { fifaCode: "BEL", name: "Bélgica" },
  { fifaCode: "IRN", name: "Irã" },
  { fifaCode: "EGY", name: "Egito" },
  { fifaCode: "NZL", name: "Nova Zelândia" },
  { fifaCode: "ESP", name: "Espanha" },
  { fifaCode: "URU", name: "Uruguai" },
  { fifaCode: "KSA", name: "Arábia Saudita" },
  { fifaCode: "CPV", name: "Cabo Verde" },
  { fifaCode: "FRA", name: "França" },
  { fifaCode: "SEN", name: "Senegal" },
  { fifaCode: "NOR", name: "Noruega" },
  { fifaCode: "IRQ", name: "Iraque" },
  { fifaCode: "ARG", name: "Argentina" },
  { fifaCode: "AUT", name: "Áustria" },
  { fifaCode: "ALG", name: "Argélia" },
  { fifaCode: "JOR", name: "Jordânia" },
  { fifaCode: "POR", name: "Portugal" },
  { fifaCode: "COL", name: "Colômbia" },
  { fifaCode: "UZB", name: "Uzbequistão" },
  { fifaCode: "COD", name: "RD Congo" },
  { fifaCode: "ENG", name: "Inglaterra" },
  { fifaCode: "CRO", name: "Croácia" },
  { fifaCode: "PAN", name: "Panamá" },
  { fifaCode: "GHA", name: "Gana" },
];